#!/usr/bin/env python3
"""One-off codegen: turns spec/testvectors.json into a checked-in C++ header
so the C++ test suite doesn't need a JSON library dependency. Re-run this
whenever spec/testvectors.json changes.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parents[2]
VECTORS_PATH = ROOT / "spec" / "testvectors.json"
OUT_PATH = Path(__file__).parent / "testvectors.hpp"


def cpp_byte_list(hex_str: str) -> str:
    b = bytes.fromhex(hex_str)
    return ", ".join(f"0x{byte:02x}" for byte in b)


def cpp_uint16_list(values: list[int]) -> str:
    return ", ".join(str(v) for v in values)


def main() -> None:
    vectors = json.loads(VECTORS_PATH.read_text())

    lines = [
        "// Auto-generated by server/tests/gen_testvectors_hpp.py from spec/testvectors.json.",
        "// Do not edit by hand -- re-run the generator instead.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <vector>",
        "",
        "struct TestVector {",
        "    std::vector<uint8_t> secret;",
        "    uint64_t time_counter;",
        "    uint8_t channel_id;",
        "    int n;",
        "    uint16_t port_low;",
        "    uint16_t port_high;",
        "    std::vector<uint16_t> expected_ports;",
        "};",
        "",
        "inline const std::vector<TestVector> kTestVectors = {",
    ]
    for v in vectors:
        lines.append("    TestVector{")
        lines.append(f"        {{{cpp_byte_list(v['secret_hex'])}}},")
        lines.append(f"        {v['time_counter']}ULL,")
        lines.append(f"        {v['channel_id']},")
        lines.append(f"        {v['N']},")
        lines.append(f"        {v['port_low']},")
        lines.append(f"        {v['port_high']},")
        lines.append(f"        {{{cpp_uint16_list(v['ports'])}}}")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"wrote {len(vectors)} vectors to {OUT_PATH}")


if __name__ == "__main__":
    main()
